'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Add Comment....
        '''</summary>
        Friend ReadOnly Property Item_Edit_Comments_AddComment_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Comments_AddComment_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Review Comments....
        '''</summary>
        Friend ReadOnly Property Item_Edit_Comments_ReviewComments_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Comments_ReviewComments_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Co&amp;mments.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Comments_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Comments_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Copy.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Copy_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Copy_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cu&amp;t.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Cut_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Cut_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;For {0}.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Add_ForCurrentUser_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForCurrentUser_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For &amp;Everyone.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Add_ForEveryone_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Add_ForEveryone_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Add.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Add_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Add_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;For {0}.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Remove_ForCurrentUser_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForCurrentUser_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to For &amp;Everyone.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Remove_ForEveryone_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_ForEveryone_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Remove.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Editable Regions.
        '''</summary>
        Friend ReadOnly Property Item_Edit_EditableRegions_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_EditableRegions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Find....
        '''</summary>
        Friend ReadOnly Property Item_Edit_Find_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Find_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Paste.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Paste_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Paste_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow &amp;Copy.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_AllowCopy_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowCopy_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow &amp;Editing Form Fields.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_AllowEditingFormFields_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowEditingFormFields_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow &amp;Formatting.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_AllowFormatting_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowFormatting_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow Formatting &amp;Styles.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_AllowFormattingStyles_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowFormattingStyles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allow &amp;Printing.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_AllowPrinting_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_AllowPrinting_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Read Only.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_ReadOnly_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_ReadOnly_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Permi&amp;ssions.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Permissions_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Permissions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pr&amp;otect Document.
        '''</summary>
        Friend ReadOnly Property Item_Edit_ProtectDocument_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_ProtectDocument_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Redo.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Redo_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Redo_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rep&amp;lace....
        '''</summary>
        Friend ReadOnly Property Item_Edit_Replace_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Replace_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select &amp;All.
        '''</summary>
        Friend ReadOnly Property Item_Edit_SelectAll_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_SelectAll_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Review Tracked Changes....
        '''</summary>
        Friend ReadOnly Property Item_Edit_TrackedChanges_ReviewTrackedChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_TrackedChanges_ReviewTrackedChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Trac&amp;ked Changes.
        '''</summary>
        Friend ReadOnly Property Item_Edit_TrackedChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_TrackedChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Track Changes.
        '''</summary>
        Friend ReadOnly Property Item_Edit_TrackedChanges_TrackChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_TrackedChanges_TrackChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Undo.
        '''</summary>
        Friend ReadOnly Property Item_Edit_Undo_Text() As String
            Get
                Return ResourceManager.GetString("Item_Edit_Undo_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Account Settings....
        '''</summary>
        Friend ReadOnly Property Item_File_CurrentUser_AccountSettings_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_CurrentUser_AccountSettings_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign &amp;Out.
        '''</summary>
        Friend ReadOnly Property Item_File_CurrentUser_SignOut_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_CurrentUser_SignOut_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}.
        '''</summary>
        Friend ReadOnly Property Item_File_CurrentUser_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_CurrentUser_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to E&amp;xit.
        '''</summary>
        Friend ReadOnly Property Item_File_Exit_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Exit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;New.
        '''</summary>
        Friend ReadOnly Property Item_File_New_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_New_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Open….
        '''</summary>
        Friend ReadOnly Property Item_File_Open_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Open_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Se&amp;tup….
        '''</summary>
        Friend ReadOnly Property Item_File_PageSetup_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_PageSetup_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Print....
        '''</summary>
        Friend ReadOnly Property Item_File_Print_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Print_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print Pre&amp;view....
        '''</summary>
        Friend ReadOnly Property Item_File_PrintPreview_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_PrintPreview_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Print &amp;Quick.
        '''</summary>
        Friend ReadOnly Property Item_File_PrintQuick_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_PrintQuick_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Recent Files.
        '''</summary>
        Friend ReadOnly Property Item_File_RecentFiles_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_RecentFiles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Save.
        '''</summary>
        Friend ReadOnly Property Item_File_Save_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Save_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save &amp;As….
        '''</summary>
        Friend ReadOnly Property Item_File_SaveAs_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_SaveAs_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign &amp;In....
        '''</summary>
        Friend ReadOnly Property Item_File_SignIn_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_SignIn_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;File.
        '''</summary>
        Friend ReadOnly Property Item_File_Text() As String
            Get
                Return ResourceManager.GetString("Item_File_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Barcode....
        '''</summary>
        Friend ReadOnly Property Item_Format_Barcode_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Barcode_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boo&amp;kmark....
        '''</summary>
        Friend ReadOnly Property Item_Format_Bookmark_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Bookmark_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;1, 2, 3.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_ArabicNumbers_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_ArabicNumbers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to As Structured &amp;List.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_AsStructuredList_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_AsStructuredList_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B&amp;ullets.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_Bullets_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Bullets_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;A, B, C.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_CapitalLetters_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_CapitalLetters_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Decrease Level.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_DecreaseLevel_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_DecreaseLevel_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to I&amp;ncrease Level.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_IncreaseLevel_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_IncreaseLevel_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to a, &amp;b, c.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_Letters_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Letters_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Properties....
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_Properties_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Properties_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;I, II, III, IV.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_RomanNumbers_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_RomanNumbers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to i, ii, iii, i&amp;v.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_SmallRomanNumbers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Bullets and &amp;Numbering.
        '''</summary>
        Friend ReadOnly Property Item_Format_BulletsAndNumbering_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_BulletsAndNumbering_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Character....
        '''</summary>
        Friend ReadOnly Property Item_Format_Character_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Character_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Colu&amp;mns....
        '''</summary>
        Friend ReadOnly Property Item_Format_Columns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Columns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit....
        '''</summary>
        Friend ReadOnly Property Item_Format_FormFields_Edit_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_Edit_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable Form &amp;Validation.
        '''</summary>
        Friend ReadOnly Property Item_Format_FormFields_EnableFormValidation_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_EnableFormValidation_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Manage Conditional Instructions....
        '''</summary>
        Friend ReadOnly Property Item_Format_FormFields_ManageConditionalInstructions_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_ManageConditionalInstructions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Form Fields.
        '''</summary>
        Friend ReadOnly Property Item_Format_FormFields_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_FormFields_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Headers and Footers....
        '''</summary>
        Friend ReadOnly Property Item_Format_HeadersAndFooters_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_HeadersAndFooters_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hype&amp;rlink....
        '''</summary>
        Friend ReadOnly Property Item_Format_Hyperlink_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Hyperlink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Image....
        '''</summary>
        Friend ReadOnly Property Item_Format_Image_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Image_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Language....
        '''</summary>
        Friend ReadOnly Property Item_Format_Language_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Language_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page Bor&amp;ders....
        '''</summary>
        Friend ReadOnly Property Item_Format_PageBorders_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_PageBorders_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page C&amp;olor....
        '''</summary>
        Friend ReadOnly Property Item_Format_PageColor_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_PageColor_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page N&amp;umber....
        '''</summary>
        Friend ReadOnly Property Item_Format_PageNumberField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_PageNumberField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Paragraph....
        '''</summary>
        Friend ReadOnly Property Item_Format_Paragraph_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Paragraph_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Body Text.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_BodyText_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level {0}.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Level_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Add to Paragraph.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_AddToParagraph_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_AddToParagraph_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Body Text.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_BodyText_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Level {0}.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Level_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Paragraph Style: {0}.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_CurrentParagraphStyle_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Paragraph Structure Le&amp;vels.
        '''</summary>
        Friend ReadOnly Property Item_Format_ParagraphStructureLevels_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_ParagraphStructureLevels_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sh&amp;ape....
        '''</summary>
        Friend ReadOnly Property Item_Format_Shape_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Shape_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Styles....
        '''</summary>
        Friend ReadOnly Property Item_Format_Styles_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Styles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tabl&amp;e of Contents....
        '''</summary>
        Friend ReadOnly Property Item_Format_TableOfContents_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_TableOfContents_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Tabs....
        '''</summary>
        Friend ReadOnly Property Item_Format_Tabs_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Tabs_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F&amp;ormat.
        '''</summary>
        Friend ReadOnly Property Item_Format_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Te&amp;xt Frame....
        '''</summary>
        Friend ReadOnly Property Item_Format_TextFrame_Text() As String
            Get
                Return ResourceManager.GetString("Item_Format_TextFrame_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Barcode.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Barcode_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Barcode_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete....
        '''</summary>
        Friend ReadOnly Property Item_Insert_Bookmark_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Bookmark_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert....
        '''</summary>
        Friend ReadOnly Property Item_Insert_Bookmark_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Bookmark_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Boo&amp;kmark.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Bookmark_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Bookmark_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;More Columns....
        '''</summary>
        Friend ReadOnly Property Item_Insert_Columns_MoreColumns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_MoreColumns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;One.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Columns_One_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_One_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Columns.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Columns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Two.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Columns_Two_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Columns_Two_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;File....
        '''</summary>
        Friend ReadOnly Property Item_Insert_File_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_File_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Footer_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Footer_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Remove.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Footer_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Footer_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to F&amp;ooter.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Footer_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Footer_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Check Box.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_CheckBox_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_CheckBox_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C&amp;ombo Box.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_ComboBox_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_ComboBox_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D&amp;ate Form Field.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_DateFormField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_DateFormField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to D&amp;elete.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Drop-Down List.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_DropDownList_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_DropDownList_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Fo&amp;rm Field.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Text Form Field.
        '''</summary>
        Friend ReadOnly Property Item_Insert_FormField_TextFormField_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_FormField_TextFormField_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Header_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Header_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Remove.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Header_Remove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Header_Remove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Header.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Header_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Header_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hyp&amp;erlink....
        '''</summary>
        Friend ReadOnly Property Item_Insert_Hyperlink_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Hyperlink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Image....
        '''</summary>
        Friend ReadOnly Property Item_Insert_Image_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Image_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Columns.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageBreaks_Column_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_Column_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Page.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageBreaks_Page_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_Page_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to P&amp;age Break.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageBreaks_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Text Wrapping.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageBreaks_TextWrapping_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageBreaks_TextWrapping_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageNumber_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageNumber_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageNumber_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageNumber_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Page Number.
        '''</summary>
        Friend ReadOnly Property Item_Insert_PageNumber_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_PageNumber_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Continuous.
        '''</summary>
        Friend ReadOnly Property Item_Insert_SectionBreaks_Continuous_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_SectionBreaks_Continuous_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Next Page.
        '''</summary>
        Friend ReadOnly Property Item_Insert_SectionBreaks_NextPage_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_SectionBreaks_NextPage_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sectio&amp;n Break.
        '''</summary>
        Friend ReadOnly Property Item_Insert_SectionBreaks_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_SectionBreaks_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Basic Shapes.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_BasicShapes_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_BasicShapes_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Block &amp;Arrows.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_BlockArrows_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_BlockArrows_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Callouts.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_Callouts_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Callouts_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Drawing Canvas.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_DrawingCanvas_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_DrawingCanvas_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Equation Shapes.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_EquationShapes_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_EquationShapes_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Flowchart.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_Flowchart_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Flowchart_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Lines.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_Lines_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Lines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Rectangles.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_Rectangles_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Rectangles_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Stars and Banners.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_StarsAndBanners_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_StarsAndBanners_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Shape.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Shape_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Shape_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sy&amp;mbol....
        '''</summary>
        Friend ReadOnly Property Item_Insert_Symbol_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Symbol_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete.
        '''</summary>
        Friend ReadOnly Property Item_Insert_TableOfContents_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert.
        '''</summary>
        Friend ReadOnly Property Item_Insert_TableOfContents_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tab&amp;le of Contents.
        '''</summary>
        Friend ReadOnly Property Item_Insert_TableOfContents_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Update.
        '''</summary>
        Friend ReadOnly Property Item_Insert_TableOfContents_Update_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TableOfContents_Update_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert.
        '''</summary>
        Friend ReadOnly Property Item_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Text Frame.
        '''</summary>
        Friend ReadOnly Property Item_Insert_TextFrame_Text() As String
            Get
                Return ResourceManager.GetString("Item_Insert_TextFrame_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C&amp;ells.
        '''</summary>
        Friend ReadOnly Property Item_Table_Delete_Cells_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Cells_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Columns.
        '''</summary>
        Friend ReadOnly Property Item_Table_Delete_Columns_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Columns_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Rows.
        '''</summary>
        Friend ReadOnly Property Item_Table_Delete_Rows_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Rows_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Table.
        '''</summary>
        Friend ReadOnly Property Item_Table_Delete_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete.
        '''</summary>
        Friend ReadOnly Property Item_Table_Delete_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Delete_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;A1 Reference Style.
        '''</summary>
        Friend ReadOnly Property Item_Table_Formulas_A1ReferenceStyle_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_A1ReferenceStyle_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Automatic &amp;Calculation.
        '''</summary>
        Friend ReadOnly Property Item_Table_Formulas_AutomaticCalculation_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_AutomaticCalculation_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Edit Formula....
        '''</summary>
        Friend ReadOnly Property Item_Table_Formulas_EditFormula_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_EditFormula_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;R1C1 Reference Style.
        '''</summary>
        Friend ReadOnly Property Item_Table_Formulas_R1C1ReferenceStyle_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_R1C1ReferenceStyle_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Formulas.
        '''</summary>
        Friend ReadOnly Property Item_Table_Formulas_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Formulas_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column To The &amp;Left.
        '''</summary>
        Friend ReadOnly Property Item_Table_Insert_ColumnToTheLeft_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_ColumnToTheLeft_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column To The &amp;Right.
        '''</summary>
        Friend ReadOnly Property Item_Table_Insert_ColumnToTheRight_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_ColumnToTheRight_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row &amp;Above.
        '''</summary>
        Friend ReadOnly Property Item_Table_Insert_RowAbove_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_RowAbove_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Row &amp;Below.
        '''</summary>
        Friend ReadOnly Property Item_Table_Insert_RowBelow_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_RowBelow_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Table....
        '''</summary>
        Friend ReadOnly Property Item_Table_Insert_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Insert.
        '''</summary>
        Friend ReadOnly Property Item_Table_Insert_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Insert_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Merge Cells.
        '''</summary>
        Friend ReadOnly Property Item_Table_MergeCells_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_MergeCells_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Properties....
        '''</summary>
        Friend ReadOnly Property Item_Table_Properties_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Properties_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to C&amp;ell.
        '''</summary>
        Friend ReadOnly Property Item_Table_Select_Cell_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Cell_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Column.
        '''</summary>
        Friend ReadOnly Property Item_Table_Select_Column_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Column_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Row.
        '''</summary>
        Friend ReadOnly Property Item_Table_Select_Row_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Row_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Table.
        '''</summary>
        Friend ReadOnly Property Item_Table_Select_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Select.
        '''</summary>
        Friend ReadOnly Property Item_Table_Select_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Select_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split &amp;Cells.
        '''</summary>
        Friend ReadOnly Property Item_Table_SplitCells_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitCells_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Above.
        '''</summary>
        Friend ReadOnly Property Item_Table_SplitTable_Above_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitTable_Above_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Below.
        '''</summary>
        Friend ReadOnly Property Item_Table_SplitTable_Below_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitTable_Below_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Split &amp;Table.
        '''</summary>
        Friend ReadOnly Property Item_Table_SplitTable_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_SplitTable_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Table.
        '''</summary>
        Friend ReadOnly Property Item_Table_Text() As String
            Get
                Return ResourceManager.GetString("Item_Table_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to B&amp;ookmark Markers.
        '''</summary>
        Friend ReadOnly Property Item_View_BookmarkMarkers_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_BookmarkMarkers_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Button Bar.
        '''</summary>
        Friend ReadOnly Property Item_View_ButtonBar_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_ButtonBar_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Always.
        '''</summary>
        Friend ReadOnly Property Item_View_Comments_Always_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Always_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Current.
        '''</summary>
        Friend ReadOnly Property Item_View_Comments_Current_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Current_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Never.
        '''</summary>
        Friend ReadOnly Property Item_View_Comments_Never_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Never_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Co&amp;mments.
        '''</summary>
        Friend ReadOnly Property Item_View_Comments_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Comments_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Control Chars.
        '''</summary>
        Friend ReadOnly Property Item_View_ControlChars_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_ControlChars_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Draft.
        '''</summary>
        Friend ReadOnly Property Item_View_Draft_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Draft_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dra&amp;wing Marker Lines.
        '''</summary>
        Friend ReadOnly Property Item_View_DrawingMarkerLines_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_DrawingMarkerLines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Always.
        '''</summary>
        Friend ReadOnly Property Item_View_EditableRegions_Always_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Always_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Current.
        '''</summary>
        Friend ReadOnly Property Item_View_EditableRegions_Current_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Current_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Never.
        '''</summary>
        Friend ReadOnly Property Item_View_EditableRegions_Never_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Never_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Editiable Regions.
        '''</summary>
        Friend ReadOnly Property Item_View_EditableRegions_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_EditableRegions_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Horizontal Ruler.
        '''</summary>
        Friend ReadOnly Property Item_View_HorizontalRuler_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_HorizontalRuler_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Page Layout.
        '''</summary>
        Friend ReadOnly Property Item_View_PageLayout_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_PageLayout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Right to Left Layout.
        '''</summary>
        Friend ReadOnly Property Item_View_RightToLeftLayout_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_RightToLeftLayout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Status Bar.
        '''</summary>
        Friend ReadOnly Property Item_View_StatusBar_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_StatusBar_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Table Gridlines.
        '''</summary>
        Friend ReadOnly Property Item_View_TableGridlines_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_TableGridlines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;View.
        '''</summary>
        Friend ReadOnly Property Item_View_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Text &amp;Frame Marker Lines.
        '''</summary>
        Friend ReadOnly Property Item_View_TextFrameMarkerLines_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_TextFrameMarkerLines_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tr&amp;acked Changes.
        '''</summary>
        Friend ReadOnly Property Item_View_TrackedChanges_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_TrackedChanges_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Vertical Ruler.
        '''</summary>
        Friend ReadOnly Property Item_View_VerticalRuler_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_VerticalRuler_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0}%.
        '''</summary>
        Friend ReadOnly Property Item_View_Zoom_Factor_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Zoom_Factor_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Zoom.
        '''</summary>
        Friend ReadOnly Property Item_View_Zoom_Text() As String
            Get
                Return ResourceManager.GetString("Item_View_Zoom_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to TX Text Control Words.
        '''</summary>
        Friend ReadOnly Property MainWindow_Caption_Product() As String
            Get
                Return ResourceManager.GetString("MainWindow_Caption_Product", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [untitled].
        '''</summary>
        Friend ReadOnly Property MainWindow_Caption_Untitled() As String
            Get
                Return ResourceManager.GetString("MainWindow_Caption_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_Error_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_Error_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occurred..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_Error_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_Error_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_NoSelection_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First select a part of the document to add a comment about it..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_NoSelection_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_NoSelection_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_PositionInvalid_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The comment wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_PositionInvalid_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_PositionInvalid_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add Comment.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_SelectionTooComplex_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The comment wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddComment_SelectionTooComplex_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddComment_SelectionTooComplex_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_Error_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to An unexpected error has occurred..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_Error_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_Error_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_NoSelection_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First select a part of the document and then choose the user who can freely edit it..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_NoSelection_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_NoSelection_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_PositionInvalid_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The editable region wasn&apos;t inserted because the specified position values (start and/or length) are invalid..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_PositionInvalid_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_PositionInvalid_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Editable Regions.
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_SelectionTooComplex_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The editable region wasn&apos;t inserted because the selection is too complex. It is not a continuous sequence of characters..
        '''</summary>
        Friend ReadOnly Property MessageBox_AddEditableRegion_SelectionTooComplex_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_AddEditableRegion_SelectionTooComplex_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The following exception is thrown:
        '''	
        '''&quot;{0}&quot;
        '''
        '''To get help, please visit the Text Control Support at www.textcontrol.com..
        '''</summary>
        Friend ReadOnly Property MessageBox_Application_ThreadException_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_Application_ThreadException_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Form Layout.
        '''</summary>
        Friend ReadOnly Property MessageBox_ChangeFormLayout_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_ChangeFormLayout_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. 
        '''Click OK to restart or Cancel to not restart the program..
        '''</summary>
        Friend ReadOnly Property MessageBox_ChangeFormLayout_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_ChangeFormLayout_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Hyperlink.
        '''</summary>
        Friend ReadOnly Property MessageBox_OpenHyperlink_CouldNotOpenLink_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Could not open link to &apos;{0}&apos;..
        '''</summary>
        Friend ReadOnly Property MessageBox_OpenHyperlink_CouldNotOpenLink_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_CouldNotOpenLink_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open linked File.
        '''</summary>
        Friend ReadOnly Property MessageBox_OpenHyperlink_FileDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The linked file &apos;{0}&apos; does not exist..
        '''</summary>
        Friend ReadOnly Property MessageBox_OpenHyperlink_FileDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenHyperlink_FileDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Recent File.
        '''</summary>
        Friend ReadOnly Property MessageBox_OpenRecentFile_FileDoesNotExist_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected file does not exist. Do you want to remove it from the list of recent files?.
        '''</summary>
        Friend ReadOnly Property MessageBox_OpenRecentFile_FileDoesNotExist_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_OpenRecentFile_FileDoesNotExist_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect Password.
        '''</summary>
        Friend ReadOnly Property MessageBox_PasswordDialog_IncorrectPassword_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered password is incorrect..
        '''</summary>
        Friend ReadOnly Property MessageBox_PasswordDialog_IncorrectPassword_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_PasswordDialog_IncorrectPassword_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to left.
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_Left() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to right.
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_Right() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to &apos;{2}&apos; were not saved.
        '''Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to To change the program&apos;s view to a {0} to {1} text appearance, the application must be restarted. Also, changes to the document were not saved.
        '''Click Yes to save these changes and restart, No to restart without saving, or Cancel to not restart..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentBeforeRestart_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentBeforeRestart_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the program closes? 
        '''Click Yes to save and close, No to close without saving, or Cancel to not close..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before the program closes? 
        '''Click Yes to save and close, No to close without saving, or Cancel to not close..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnExit_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnExit_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before a new document is created? 
        '''Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before a new document is created? 
        '''Click Yes to save and create, No to create without saving, or Cancel to not to create a new document..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnNew_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnNew_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open.
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save changes to &apos;{0}&apos; before the new document is opened? 
        '''Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_ToFile() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_ToFile", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do you want to save the document before the new document is opened? 
        '''Click Yes to save and open, No to open without saving, or Cancel to not to open the new document..
        '''</summary>
        Friend ReadOnly Property MessageBox_SaveDirtyDocumentOnOpen_Untitled() As String
            Get
                Return ResourceManager.GetString("MessageBox_SaveDirtyDocumentOnOpen_Untitled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Table Of Contents.
        '''</summary>
        Friend ReadOnly Property MessageBox_UpdateTableOfContents_NoContents_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No table of contents entries found..
        '''</summary>
        Friend ReadOnly Property MessageBox_UpdateTableOfContents_NoContents_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UpdateTableOfContents_NoContents_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign Out.
        '''</summary>
        Friend ReadOnly Property MessageBox_UserAccess_SignOut_Caption() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} was successfully signed out..
        '''</summary>
        Friend ReadOnly Property MessageBox_UserAccess_SignOut_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccess_SignOut_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to By deleting the account, the current user will be signed out. Click OK to proceed or Cancel to not delete the account..
        '''</summary>
        Friend ReadOnly Property MessageBox_UserAccessDialogDeleteAccount_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccessDialogDeleteAccount_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The entered password does not match the given user&apos;s password..
        '''</summary>
        Friend ReadOnly Property MessageBox_UserAccessDialogIncorrectPassword_Text() As String
            Get
                Return ResourceManager.GetString("MessageBox_UserAccessDialogIncorrectPassword_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hide Tracked Changes.
        '''</summary>
        Friend ReadOnly Property Method_SetTrackedChangesHighlightMode_HideTrackedChanges() As String
            Get
                Return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HideTrackedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Highlight Tracked Changes.
        '''</summary>
        Friend ReadOnly Property Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges() As String
            Get
                Return ResourceManager.GetString("Method_SetTrackedChangesHighlightMode_HighlightTrackedChanges", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property PasswordDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend ReadOnly Property PasswordDialog_Caption() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enter a password to open the document..
        '''</summary>
        Friend ReadOnly Property PasswordDialog_EnterPassword() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_EnterPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property PasswordDialog_OK() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Password:.
        '''</summary>
        Friend ReadOnly Property PasswordDialog_Password() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_Password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The document &apos;{0}&apos; is protected..
        '''</summary>
        Friend ReadOnly Property PasswordDialog_ProtectedDocument() As String
            Get
                Return ResourceManager.GetString("PasswordDialog_ProtectedDocument", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Column: .
        '''</summary>
        Friend ReadOnly Property StatusBar_Column() As String
            Get
                Return ResourceManager.GetString("StatusBar_Column", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line: .
        '''</summary>
        Friend ReadOnly Property StatusBar_Line() As String
            Get
                Return ResourceManager.GetString("StatusBar_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Page: .
        '''</summary>
        Friend ReadOnly Property StatusBar_Page() As String
            Get
                Return ResourceManager.GetString("StatusBar_Page", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Section: .
        '''</summary>
        Friend ReadOnly Property StatusBar_Section() As String
            Get
                Return ResourceManager.GetString("StatusBar_Section", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account Settings.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_AccountSettings_Caption() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Confirm Password:.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_AccountSettings_ConfirmPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_ConfirmPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Delete Account.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_AccountSettings_Delete() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_Delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;New Password:.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_AccountSettings_NewPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_NewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Old Password:.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_AccountSettings_OldPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_AccountSettings_OldPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_Cancel() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Create New User Account.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_CreateAccount_Caption() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_CreateAccount_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Confirm Password:.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_CreateAccount_ConfirmPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_CreateAccount_ConfirmPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;New Password:.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_CreateAccount_NewPassword() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_CreateAccount_NewPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_OK() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sign In.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_SignIn_Caption() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_SignIn_Caption", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;Password:.
        '''</summary>
        Friend ReadOnly Property UserAccessDialog_SignIn_Password() As String
            Get
                Return ResourceManager.GetString("UserAccessDialog_SignIn_Password", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
